Refactored goland script to align to new environment setup

diff --git a/goland b/goland
--- a/goland
+++ b/goland
@@ -3,23 +3,40 @@
 [ ! -z "$CLOUD_SHELL" ] && ENV=cloud || ENV=mac
 source ./env/env.sh $ENV
 
-if [ $(export | grep -c DISPLAY) -gt 0 ]
+if [[ ! -z DISPLAY ]]
 then
-  PORT=$(ps -ef | grep "Xquartz :\d" | grep -v xinit | awk '{ print $9; }')
-  X11_PATH=${DISPLAY/:0}
-  display="--env DISPLAY=host.docker.internal${PORT}"
-else
-  display=""
+  echo "${X11_ERROR}"
+  exit 1
 fi
 
-docker pull rycus86/goland:latest
-docker run --rm \
-  --detach \
-  ${display} \
-  --security-opt=seccomp:unconfined \
-  --volume ${X11_PATH}:/tmp/.X11-unix \
-  --volume ~/.GoLand:/home/developer/.GoLand \
-  --volume ~/.GoLand.java:/home/developer/.java \
-  --volume ~/Development/go:/home/developer/go \
-  --name goland-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
-  rycus86/goland:latest
+function setup_env_vars() {
+  if [ $(export | grep -c DISPLAY) -gt 0 ]
+  then
+    PORT=$(ps -ef | grep "Xquartz :\d" | grep -v xinit | awk '{ print $9; }')
+    X11_PATH=${DISPLAY/:0}
+    display="--env DISPLAY=host.docker.internal${PORT}"
+  else
+    display=""
+  fi
+}
+
+function pull_latest() {
+  docker pull ${GOLAND}
+}
+
+function run() {
+  docker run --rm \
+             --detach \
+             ${display} \
+             --security-opt=seccomp:unconfined \
+             --volume ${X11_PATH}:/tmp/.X11-unix \
+             --volume ~/.GoLand:/home/developer/.GoLand \
+             --volume ~/.GoLand.java:/home/developer/.java \
+             --volume $WORKSPACE/go:/home/developer/go \
+             --name goland-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
+             ${GOLAND}
+}
+
+setup_env_vars
+pull_latest
+run
